import re

# 1. OUR PYTHON TOOL
def calculator(a, b):
    return a + b

def main():
    conversation_memory = []

    print("🛠️ Tool Calling Tracker Started.")
    print("Try typing: 'Please add 5 and 10'")
    print("Type 'quit' to exit.\n")

    while True:
        user_input = input("You: ")
        if user_input.lower() == 'quit':
            break

        # Step 1: Save User message to memory
        conversation_memory.append({"role": "user", "content": user_input})

        # --- FAKE AI LOGIC START ---
        # If the user asks to "add" and provides numbers, the fake AI triggers a tool!
        numbers = [int(s) for s in re.findall(r'\b\d+\b', user_input)]
        
        if "add" in user_input.lower() and len(numbers) >= 2:
            num1, num2 = numbers[0], numbers[1]
            
            print("\n[ 🛑 DETOUR: Fake LLM decides to use a tool! ]")
            
            # Step 2: The LLM outputs a "tool_use" block instead of text
            tool_use_message = {
                "role": "assistant",
                "content": [
                    {
                        "type": "tool_use",
                        "id": "toolu_987654321",  # A random ID generated by the API
                        "name": "calculator",
                        "input": {"a": num1, "b": num2}
                    }
                ]
            }
            conversation_memory.append(tool_use_message)
            
            # Step 3: Our Python script (the Harness) intercepts this and runs the tool
            print(f"[ ⚙️ HARNESS: Running calculator({num1}, {num2}) in Python... ]")
            result = calculator(num1, num2)
            print(f"[ ⚙️ HARNESS: The result is {result}. Sending it back to memory... ]\n")
            
            # Step 4: We package the result into a "tool_result" block for the LLM
            tool_result_message = {
                "role": "user",
                "content": [
                    {
                        "type": "tool_result",
                        "tool_use_id": "toolu_987654321", # Must match the ID above!
                        "content": str(result)
                    }
                ]
            }
            conversation_memory.append(tool_result_message)
            
            # Step 5: The LLM reads the result and gives a final text answer
            final_answer = f"The sum of {num1} and {num2} is {result}!"
            conversation_memory.append({"role": "assistant", "content": final_answer})
            
            print(f"Agent: {final_answer}\n")

        else:
            # Normal conversation without tools
            ai_text = "I am a practice bot! Ask me to add two numbers."
            conversation_memory.append({"role": "assistant", "content": ai_text})
            print(f"Agent: {ai_text}\n")
        # --- FAKE AI LOGIC END ---

        # PEEK BEHIND THE CURTAIN: Print the actual memory structure!
        print("--- CURRENT MEMORY STATE ---")
        for index, message in enumerate(conversation_memory):
            print(f"\n[{index}] Role: {message['role'].upper()}")
            print(f"    Content: {message['content']}")
        print("-" * 28 + "\n")

if __name__ == "__main__":
    main()